version: '3.3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-aeroporto
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: aeroporto
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
